name: Deploy to server

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        eval $(ssh-agent -s)
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan archer.porte7.com >> ~/.ssh/known_hosts

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install rsync -y

    - name: Deploy to Staging
      run: |
        SERVER=archer.porte7.com
        SERVICE_PATH=/datafs/dev/
        SERVICE_NAME=wp-test
        PROJECT_NAME=wp-test

        # Créer les répertoires distants s'ils n'existent pas
        ssh $SERVER "mkdir -p $SERVICE_PATH/$PROJECT_NAME" || exit 1

        # Définir les autorisations
        ssh $SERVER "chmod 755 $SERVICE_PATH $SERVICE_PATH/$PROJECT_NAME" || exit 1

        # Copier les fichiers avec rsync
        rsync -arouvH --exclude='.git' --exclude='node_modules' ./ $SERVER:${SERVICE_PATH}/${PROJECT_NAME} || exit 1